export const WORKSPACES = [
  { id: "overview", label: "Overview", icon: "LayoutDashboard" },
  { id: "clients", label: "Clients", icon: "Users" },
  { id: "rooms", label: "Video Rooms", icon: "Video" },
  { id: "events", label: "Events", icon: "Calendar" },
  { id: "finance", label: "Finance", icon: "DollarSign" },
  { id: "website", label: "Website", icon: "Globe" },
  { id: "inventory", label: "Inventory", icon: "Package" },
  { id: "ops", label: "Ops Hub", icon: "Wrench" },
  { id: "strategy", label: "Strategy", icon: "Target" },
  { id: "messages", label: "Messages", icon: "MessageSquare" },
  { id: "notes", label: "Notes", icon: "FileText" },
  { id: "media", label: "Media", icon: "Image" },
  { id: "command", label: "Live Command", icon: "Zap" },
] as const;

export type WorkspaceId = (typeof WORKSPACES)[number]["id"];

export const ROOM_TEMPLATES = [
  {
    id: "discovery-call",
    name: "Discovery Call",
    duration: 45,
    icon: "Search",
    agenda: [
      "Introductions & rapport building",
      "Understand event vision & goals",
      "Discuss budget range & guest count",
      "Review available dates & venues",
      "Next steps & follow-up plan",
    ],
    prep: "Review inquiry form, prepare availability calendar",
    tools: ["Notes", "Calendar"],
  },
  {
    id: "design-review",
    name: "Design Review",
    duration: 60,
    icon: "Palette",
    agenda: [
      "Review mood board & color palette",
      "Floor plan walkthrough",
      "Table settings & centerpiece options",
      "Lighting & ambiance discussion",
      "Vendor visual samples",
      "Client approvals",
    ],
    prep: "Update mood board, prepare floor plan draft",
    tools: ["Mood Board", "Floor Plan", "Approvals"],
  },
  {
    id: "final-walkthrough",
    name: "Final Walkthrough",
    duration: 90,
    icon: "CheckSquare",
    agenda: [
      "Complete timeline review",
      "Vendor confirmations & contacts",
      "Floor plan final approval",
      "Emergency protocols review",
      "Day-of communication plan",
      "Final questions & concerns",
      "Sign-off on all details",
    ],
    prep: "Finalize all vendor contracts, complete timeline, print emergency contacts",
    tools: ["Floor Plan", "Approvals", "Checklist", "Contacts"],
  },
  {
    id: "vendor-meet",
    name: "Vendor Meet",
    duration: 30,
    icon: "Handshake",
    agenda: [
      "Vendor introduction to client",
      "Service overview & pricing",
      "Portfolio review",
      "Q&A",
    ],
    prep: "Brief vendor on client preferences, prepare comparison sheet",
    tools: ["Notes", "Approvals"],
  },
  {
    id: "day-of-briefing",
    name: "Day-Of Briefing",
    duration: 20,
    icon: "Clock",
    agenda: [
      "Timeline quick review",
      "Staff assignments confirmed",
      "Weather & contingency check",
      "Final vendor check-in",
    ],
    prep: "Print timeline cards, charge all devices, test walkie-talkies",
    tools: ["Checklist", "Contacts"],
  },
] as const;

